before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7

archives:
 -
  format: tar.gz
  name_template: "{{.Os}}-{{.Arch}}{{if .Arm}}v{{.Arm}}{{end}}-{{ .ProjectName }}"
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
  format_overrides:
    - goos: windows
      format: zip

checksum:
  name_template: 'checksums.txt'
